Sahar implement view state and Detail Character UI
sahar-as/RickAndMorty pull request #3
Opened 2023-06-14 11:46 UTC by sahar-as

Report:
- Adding Progress bar to character UI
- Implement view state for character UI
- Implement API of Detail Character +its Repository + its use case
- Design and develop detail character UI part

2023-06-14 12:13 UTC, FarshidRoohi requested changes

2023-06-14 12:13 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/characters_screen/CharactersFragment.kt
> +        lifecycleScope.launch {
Use ViewState and data class for update view

2023-06-14 12:13 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/characters_screen/CharactersViewModel.kt
>      private val _charactersList = MutableStateFlow<List<Character>>(emptyList())
Use Single mutableStateFlow for data and state

2023-06-14 12:13 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/detail_character/DetailCharacterFragment.kt
> +                        imgCharacterPicture.load(detailCharacter.image)
You can write a function and pass model and populate data

2023-06-14 12:13 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/detail_character/DetailCharacterViewModel.kt
> +    val id = savedStateHandle.get<Int>("CharacterId")
Remove android components and handle in the UI elements(fragment)

2023-06-14 12:13 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/detail_character/DetailCharacterViewModel.kt
> +                val episodes = mutableListOf<Episode>()
Move this block to UseCase for reusable code

2023-06-14 12:13 UTC, FarshidRoohi commented on app/src/main/res/layout/item_detail_character.xml
> +        app:cardBackgroundColor="#75D8FB"
Use resource for color, strings,  dimen

2023-06-17 05:59 UTC, sahar-as commented
Edited Parts:
- Remove the Save State handler from VM and put it in the Fragment
- Transfer getting Episode list from VM and put it to the Use Case
- Implement ViewState in both Fragments (*please check extension function)
- Using resource files for color & text

New Parts:
- Implement Room Database
- Change the logic of remote repository ( => after getting data it will save it to DB)

2023-06-17 07:52 UTC, FarshidRoohi requested changes

2023-06-17 07:52 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/domain/model/DetailCharacterViewState.kt
> +    val detailCharacter: DetailCharacter = DetailCharacter(1,"","","","","", emptyList()),
Remove dummy data

2023-06-17 07:52 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/domain/usecase/CharactersUseCase.kt
> +            val id = episode.split("episode/")[1]
Fix this issue and crash because maybe we have crash

2023-06-17 07:52 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/characters_screen/CharactersViewModel.kt
> +//fun <T> T.updateState(newState: T.() -> T) {
```
fun <T> MutableStateFlow<T>.updateState(newState: T.() -> T) {
    value = newState(value)
}
```

2023-06-17 07:52 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/detail_character/DetailCharacterFragment.kt
> +    private lateinit var binding: FragmentDetailCharacterBinding
```
val viewModel = ...

val binding = ...
val bindingController = ...


class MyClass {

val name = ...

fun set(){
}

}
```

2023-06-17 07:52 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/detail_character/DetailCharacterFragment.kt
> +                        binding.pbLoading.visibility = View.INVISIBLE
It's work and fine but you can write a function for this block of code

2023-06-17 07:52 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/detail_character/DetailCharacterViewModel.kt
> +fun <T> T.update(newState: T.() -> T): T{
Remove extension function and move to utilities

2023-06-17 07:52 UTC, FarshidRoohi commented
Change package name and remove `underline`

2023-06-17 12:42 UTC, sahar-as commented
Edit Part:
- Edit extension function, move extension function to Screen
- Edit split to spilt.getOrElse(1){""}
- Remove dummy data in viewstate

New Part:
- Implement data class for Room database
- Create Local repository
- Edit remote repository

2023-06-17 13:02 UTC, FarshidRoohi requested changes

2023-06-17 13:02 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/detailcharacter/DetailCharacterFragment.kt
> +                    ViewState.SUCCESS -> { onSuccessState(viewState.detailCharacter!!, viewState.episodeList) }
Pass null and check it

2023-06-17 13:37 UTC, sahar-as commented
Edit:
- Add lastOrNull to split and check if it is null or not
- Edit two convert functions and make them more concise
- Change name: viewState to viewStateFlow
- Check the nullability of character info in the DetailCharacterFragment

2023-06-17 14:17 UTC, FarshidRoohi requested changes

2023-06-17 14:17 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/data/repository/CharactersRemoteRepositoryImpl.kt
> +                id = characterDto.id,
Sahar it's ok, but you can write better for reusable code

2023-06-17 14:17 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/domain/usecase/CharactersUseCase.kt
> +            id?.let {
If id is empty string?

2023-06-17 14:17 UTC, FarshidRoohi commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/detailcharacter/DetailCharacterFragment.kt
> +                        viewState.detailCharacter?.let { onSuccessState(it, viewState.episodeList) }
In this case you added new bracket in the block but you can pass nullable item and check it in the function.
because it's more readable and less blocks

2023-06-17 14:19 UTC, sahar-as commented on app/src/main/java/ir/saharapps/rickandmorty/ui/screen/detailcharacter/DetailCharacterFragment.kt
> +                        viewState.detailCharacter?.let { onSuccessState(it, viewState.episodeList) }
ok got it

2023-06-17 14:33 UTC, sahar-as commented on app/src/main/java/ir/saharapps/rickandmorty/domain/usecase/CharactersUseCase.kt
> +            id?.let {
got it

2023-06-17 14:36 UTC, sahar-as commented on app/src/main/java/ir/saharapps/rickandmorty/domain/usecase/CharactersUseCase.kt
> +            id?.let {
Done

2023-06-18 06:34 UTC, sahar-as commented
Edit:
Create an extension function for the convert character method and remove redundant function

2023-06-18 07:09 UTC, merged